apiVersion: 1

datasources:
  - name: Celery-Worker
    type: prometheus
    uid: celery-worker
    access: proxy
    url: http://prometheus_celery:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST